version: '3'

services:
    nginx:
        image: ghcr.io/alxvgt/icalprocessor:latest
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.icalprocessor.rule=Host(`icalprocessor.418.ovh`)"
                - "traefik.http.routers.icalprocessor.tls=true"
                - "traefik.http.routers.icalprocessor.tls.certresolver=mytlschallenge"
                - "traefik.http.services.icalprocessor.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        networks:
            - shared-proxy


networks:
    shared-proxy:
        external: true