services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80

        volumes:
            - ./php/:/var/www/html/

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - ./php/:/var/www/html/